### ISSUE TITLE
GTK4 backend needs upgrade of GTK3

### ISSUE THREAD

**Issue by nclettiere** [nclettiere/C99Quester#1]
### Problem
The classes [imgui_impl_gtk4.cpp ](https://github.com/Noriaki-Kakyoin/C99Quester/blob/master/imgui/impl/imgui_impl_gtk4.cpp)& [imgui_impl_gtk4.h](https://github.com/Noriaki-Kakyoin/C99Quester/blob/master/imgui/impl/imgui_impl_gtk4.h) are written to support GTK3 and C++ version of ImGui. The project assumes GTK4 and CImGui.

### Solution
Straight forward, write the equivalent code of GTK4 and easily replace ImGui fuctions.

**Comment by Noriaki-Kakyoin** [comment]
GTK4 API docs:
Clipboard documentation [here](https://developer.gnome.org/gtk4/unstable/ch41s02.html#id-1.7.4.4.15)
